# Generated by Django 5.0.6 on 2024-05-08 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=50)),
                ('website', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tematicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=30)),
                ('Codigo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('dia_publicacion', models.DateField()),
                ('autores', models.ManyToManyField(to='principal.autores')),
                ('tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.tematicas')),
            ],
        ),
    ]
